### ISSUE TITLE
QTaste starts in "degraded mode"

### ISSUE THREAD

**Issue by pguermo** [qspin/qtaste#218]
Some edition functions are not working (eg: clic on a lib to open it) when QTaste has started with this exception.

Exception in thread "Thread-4" java.lang.VerifyError: class com.sun.script.jython.JythonScope overrides final method __findattr__.(Ljava/lang/String;)Lorg/python/core/PyObject;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.sun.script.jython.JythonScriptEngineFactory.getScriptEngine(JythonScriptEngineFactory.java:132)
        at javax.script.ScriptEngineManager.getEngineByName(Unknown Source)
        at com.qspin.qtaste.testsuite.impl.JythonTestScript.<clinit>(JythonTestScript.java:113)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.qspin.qtaste.kernel.engine.TestEngine.lambda$static$0(TestEngine.java:79)
        at java.lang.Thread.run(Unknown Source)

Restarting QTaste fix the problem but the problem may occur again... until you are lucky.

This problem has been reproduced on different PC (windows & java 1.8)

**Comment by pguermo** [comment]
The testapi had some dependecies to jython 2.5.
The problem is fixed by chaning this dependency to jython 2.7.
Thanks David.
